### PR TITLE
Closes #1134: Introduce a common functionality for retrieving resources

### LINKED ISSUE #1134: Fix multibranch build failing when more than one build is being run in parallel
I just noticed the multibranch build for a newly created branch `marekhorst_1132_fix_http_connection_pool_handling` has failed:

http://ci.ceon.pl/job/iis_build_multibranch/job/marekhorst_1132_fix_http_connection_pool_handling/2/

with the following unit test error:

```
Path does not exist: file:/srv/yadda-jenkins/app/workspace/tp_connection_pool_handling-7BTP7MM64PLLYOZDVA67NVVWYNKYYC65ZRPJFHBI7E5YN4CASU6A%402/iis-wf/iis-wf-import/target/test-classes/eu/dnetlib/iis/wf/importer/patent/sampletest/oozie_app/input/patents_epo.tsv;
```

I've seen similar errors before but just did care too much, I thought those are some problems of an intermittent kind.

It looks like the path contains the `%402` character which might be the cause of the problem (the test run locally succeeds).

When I looked at the set of all the jobs being run for the branch:
http://ci.ceon.pl/job/iis_build_multibranch/job/marekhorst_1132_fix_http_connection_pool_handling/
I found two of them, triggered almost at the same time. I guess the first one was triggered after the branch was pushed to the origin repository while the second when issuing a pull request. @przemyslawjacewicz, could it be the case?

Anyway, if the two executions were expected then we are left with one issue to be solved only:)

I have found one resource describing very similar issue:
https://stackoverflow.com/questions/39553523/jenkins-failures-due-to-an-extra-402-character-in-the-location-address
which might be helpful in solving our problem.

### PR DESCRIPTION
**Pull request by przemyslawjacewicz**
Inside this PR
* introduction of `eu.dnetlib.iis.common.StaticResourceProvider` with utility methods for handling resources on classpath: finding resource path and resource content
* making use of `eu.dnetlib.iis.common.StaticResourceProvider` for handling resources
* various cleanups due to new utility class
  * removal of unnecessary methods and code parts for retrieving resource paths or contents in production code and in tests
  * fixes to related code parts e.g. description updates

Note: `eu.dnetlib.iis.common.StaticResourceProviderTest` uses a new test method naming convention: `public void given_when_then()`. I've included it as an experiment, I think it's quite convenient.  However, if opinions will differ I can change it to our usual style.

### CODE REVIEW

File: iis-common/src/main/java/eu/dnetlib/iis/common/StaticResourceProvider.java [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+
+import java.io.IOException;
+import java.io.InputStream;
+import java.io.InputStreamReader;
+import java.nio.charset.StandardCharsets;
+import java.util.Arrays;
+import java.util.List;
+import java.util.stream.Collectors;
+
+public class StaticResourceProvider {
```
Comment (marekhorst) [inline iis-common/src/main/java/eu/dnetlib/iis/common/StaticResourceProvider.java:14]: I guess we could add a brief javadoc description for this class.

And one minor remark: since all the methods from this class are relying on classpath resources then maybe it would more informative when renaming `StaticResourceProvider` to `ClassPathResourceProvider`. What do you think?

**Review by marekhorst — CHANGES_REQUESTED** [review]
Just a few minor remarks on potential improvements.

File: iis-common/src/main/java/eu/dnetlib/iis/common/StaticResourceProvider.java [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+        }
+    }
+
+    /**
+     * Returns the input stream reader of a resource on the classpath.
+     *
+     * @param location String indicating the location of resource on the classpath.
+     * @return InputStreamReader of the resource.
+     */
+    public static InputStreamReader getResourceInputStreamReader(String location) {
```
Comment (mpol) [inline iis-common/src/main/java/eu/dnetlib/iis/common/StaticResourceProvider.java:76]: Maybe `Reader getResourceReader(String location)`?

File: iis-common/src/main/java/eu/dnetlib/iis/common/StaticResourceProvider.java [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+    public static InputStream getResourceInputStream(String location) {
+        try {
+            return new ClassPathResource(location).getInputStream();
+        } catch (IOException e) {
+            throw new RuntimeException(e);
+        }
+    }
+
+    /**
+     * Returns the input stream reader of a resource on the classpath.
```
Comment (mpol) [inline iis-common/src/main/java/eu/dnetlib/iis/common/StaticResourceProvider.java:71]: Maybe it should mention that it uses UTF-8?

File: iis-common/src/main/java/eu/dnetlib/iis/common/StaticResourceProvider.java (hunk 1 above)
Comment (mpol) [reply iis-common/src/main/java/eu/dnetlib/iis/common/StaticResourceProvider.java:14]: +1 for Javadoc
The `StaticResourceProvider` name at least would need some explanation. And I have no intuition if `ClassPathResourceProvider` is right or too much of an implementation-detail name but all the docs below mention classpath, so maybe it would be a better name?

File: iis-wf/iis-wf-affmatching/src/test/java/eu/dnetlib/iis/wf/affmatching/AffMatchingJobTest.java [hunk 4]
```diff
@@ -82,15 +83,22 @@ public void affiliationMatchingJob() throws IOException {
...
+        String jsonInputInferredDocProjPath = StaticResourceProvider
+                .getResourcePath("data/input/docProjInferred.json");
+        String jsonInputDocProjPath = StaticResourceProvider
+                .getResourcePath("data/input/docProj.json");
+        String jsonInputProjOrgPath = StaticResourceProvider
+                .getResourcePath("data/input/projOrg.json");
+
+        String jsonOutputPath = StaticResourceProvider
+                .getResourcePath("data/expectedOutput/matchedOrganizations.json");
+        String jsonOutputReportPath = StaticResourceProvider
```
[the remark this answers is not in the document]
Comment (przemyslawjacewicz) [reply iis-wf/iis-wf-affmatching/src/test/java/eu/dnetlib/iis/wf/affmatching/AffMatchingJobTest.java:100]: Yes, you're right, but I'd say that it's not a real drawback and can add to code readability. Bounding resources to packages makes clear where the resource is used.

File: iis-common/src/main/java/eu/dnetlib/iis/common/StaticResourceProvider.java (hunk 1 above)
Comment (przemyslawjacewicz) [reply iis-common/src/main/java/eu/dnetlib/iis/common/StaticResourceProvider.java:14]: Yes, I thought of renaming the class to :) Plus adding class javadoc.

**Comment by przemyslawjacewicz** [comment]
I've pushed code review changes.

**Review by marekhorst — APPROVED** [review]
LGTM.
